# Generated by Django 3.1.1 on 2021-01-29 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20201219_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iopaper',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='subcoursebooks',
            name='acayear',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
    ]
