# Generated by Django 3.1.1 on 2021-02-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_pes_petakenbystudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petakenbystudent',
            name='PE',
        ),
        migrations.RemoveField(
            model_name='petakenbystudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='PEs',
        ),
        migrations.DeleteModel(
            name='PETakenByStudent',
        ),
    ]
