# Generated by Django 3.2.7 on 2021-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20210227_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcewebinars',
            name='certification',
            field=models.CharField(default='https://storage.googleapis.com/coeus-1482f.appspot.com/jrJHaAmxio5spt4okAh6Pi.pdf', max_length=500),
        ),
    ]
