# Generated by Django 3.1.4 on 2020-12-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20201217_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wceconferences',
            old_name='confname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wcefdp',
            old_name='place',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='wcesttp',
            old_name='place',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='wceworkshops',
            old_name='place',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='wceconferences',
            name='place',
        ),
        migrations.AddField(
            model_name='wcewebinars',
            name='domain',
            field=models.CharField(default='CSE', max_length=40),
        ),
        migrations.AlterField(
            model_name='iopaper',
            name='index',
            field=models.CharField(default='SCI', max_length=30),
        ),
        migrations.AlterField(
            model_name='wceconferences',
            name='index',
            field=models.CharField(default='SCI', max_length=30),
        ),
    ]
