# Generated by Django 3.1.1 on 2021-02-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_isda'),
        ('teacher', '0004_auto_20210129_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2021', max_length=4)),
                ('sem', models.CharField(default='2', max_length=1)),
                ('courseName', models.CharField(default='FLAT', max_length=100)),
                ('courseCode', models.CharField(default='4CS101', max_length=20)),
                ('acadYear', models.CharField(default='SE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PETakenByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.pes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
