# Generated by Django 3.1.1 on 2020-12-13 12:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(default='WCE Hackathon', max_length=50)),
                ('organizer', models.CharField(default='Walchand College of Engineering, Sangli', max_length=60)),
                ('location', models.CharField(default='Sangli', max_length=15)),
                ('mode', models.BooleanField()),
                ('projectTitle', models.CharField(default='No Title', max_length=45)),
                ('description', models.TextField(default='No description')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('winner', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kala', max_length=30)),
                ('organizer', models.CharField(default='WCE', max_length=30)),
                ('location', models.CharField(default='Sangli', max_length=50)),
                ('mode', models.BooleanField()),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('certification', models.URLField()),
                ('certBool', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kala', max_length=30)),
                ('organizer', models.CharField(default='WCE', max_length=30)),
                ('location', models.CharField(default='Sangli', max_length=50)),
                ('domain', models.CharField(default='CSE', max_length=30)),
                ('mode', models.BooleanField()),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('certification', models.URLField()),
                ('certBool', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certBool', models.BooleanField(default=False)),
                ('certification', models.URLField(default='NA')),
                ('comps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.competitions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRN', models.CharField(max_length=20, unique=True)),
                ('dept', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('elective', models.CharField(default='NA', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paperpublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papertitle', models.CharField(default='Research Paper', max_length=100)),
                ('mode', models.BooleanField()),
                ('confname', models.CharField(default='No Title', max_length=100)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='Sangli', max_length=100)),
                ('level', models.BooleanField()),
                ('publicationPorR', models.BooleanField()),
                ('publicationtype', models.CharField(default='Book Chapter', max_length=100)),
                ('index', models.CharField(default='8888888888', max_length=30)),
                ('volumenumber', models.IntegerField()),
                ('issuenumber', models.IntegerField()),
                ('isbnissndoi', models.CharField(default='ISBN', max_length=20)),
                ('pagefrom', models.IntegerField()),
                ('pageto', models.IntegerField()),
                ('month', models.CharField(default='September', max_length=15)),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('paperurl', models.URLField(default='http://www.sciencedirect.com/science/article/pii/S0747563216304411')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='C++', max_length=30)),
                ('domain', models.CharField(default='CSE', max_length=30)),
                ('platform', models.CharField(default='Udemy', max_length=30)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('certification', models.URLField()),
                ('certBool', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.paperpublications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
