# Generated by Django 3.1.4 on 2020-12-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201217_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='papers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.paperpublications'),
        ),
    ]
