# Generated by Django 3.1.4 on 2021-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_gate_gre_internship_placements_startup_toefl'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='companyName',
            field=models.CharField(default='Morgan Stanley', max_length=30),
        ),
        migrations.AddField(
            model_name='internship',
            name='mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='intershipType',
            field=models.BooleanField(default=True),
        ),
    ]
