# Generated by Django 3.1.4 on 2021-01-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210130_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='intershipType',
            new_name='internshipType',
        ),
    ]
