# Generated by Django 3.1.4 on 2021-02-04 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yearOfEnrollment',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
        migrations.AddField(
            model_name='student',
            name='yearOfGraduation',
            field=models.CharField(default='NA.Enter after 4th year results', max_length=4),
        ),
    ]
