# Generated by Django 3.1.4 on 2020-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201215_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpublications',
            name='isbnissndoi',
            field=models.CharField(default='ISBN', max_length=20, unique=True),
        ),
    ]
