# Generated by Django 3.1.4 on 2020-12-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201217_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpublications',
            name='isbnissndoi',
            field=models.CharField(default='ISBN', max_length=20),
        ),
    ]
