# Generated by Django 3.1.4 on 2020-12-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='papers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.paperpublications'),
        ),
    ]
