# Generated by Django 3.1.4 on 2021-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210130_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='testDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
