# Generated by Django 3.1.5 on 2021-02-02 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0012_auto_20210131_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('guideName', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=20)),
                ('semester', models.IntegerField(default=1, null=True)),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('socialCause', models.BooleanField(default=False)),
                ('cause', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
