# Generated by Django 3.1.4 on 2021-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210204_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='yearOfEnrollment',
            field=models.CharField(default='NA', max_length=4),
        ),
    ]
