# Generated by Django 3.1.4 on 2021-02-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20210204_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isDA',
            field=models.BooleanField(default=False),
        ),
    ]
