# Generated by Django 3.1.4 on 2021-03-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_isda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='elective',
        ),
    ]
