from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'HOD'
urlpatterns = [
    path('/', include([
        path('addFaculty', views.addFaculty.as_view(), name="addFaculty"),
        path('HODHome', views.HODHome, name="HODHome"),
        path('addCourseExitSurvey', views.addCourseES.as_view(), name="addCourseES"),
        path('CourseExitSurveys', views.courseES.as_view(), name="courseES"),
        path('addDepartmentFeedbackSurvey', views.addDeptFS.as_view(), name="addDepartmentFeedbackSurvey"),
        path('DepartmentFeedbackSurveys', views.deptFS.as_view(), name="DepartmentFeedbackSurveys"),
        path('addGraduationExitSurvey', views.addGradES.as_view(), name="addGraduationExitSurvey"),
        path('GraduationExitSurveys', views.gradES.as_view(), name="GraduationExitSurveys"),
        path('delete_items/<str:ido>/<str:pagetype>', views.delete_items, name="delete_items"),
        path('queries/', include([
            path('FDPqueries', views.FDPqueries.as_view(), name="FDPqueries"),
            path('FDPqueryResult/<str:email>/<str:option>/<str:year>', views.FDPqueryResult.as_view(), name="FDPqueryResult"),
            path('Workshopqueries', views.Workqueries.as_view(), name="Workshopqueries"),
            path('WorkshopqueryResult/<str:email>/<str:option>/<str:year>', views.WorkshopqueryResult.as_view(), name="WorkshopqueryResult"),
            path('Paperqueries', views.Paperqueries.as_view(), name="Paperqueries"),
            path('PaperqueryResult/<str:email>/<str:year>', views.PaperqueryResult.as_view(), name="PaperqueryResult"),
            path('GuestLecturequeries', views.GLqueries.as_view(), name="GuestLecturequeries"),
            path('GuestLecturequeryResult/<str:email>/<str:year>', views.GuestLecturequeryResult.as_view(), name="GuestLecturequeryResult"),
            path('OnlineCoursequeries', views.Coursequeries.as_view(), name="OnlineCoursequeries"),
            path('OnlineCoursequeryResult/<str:email>/<str:year>', views.OnlineCoursequeryResult.as_view(), name="OnlineCoursequeryResult"),
            path('Webinarqueries', views.Webinarqueries.as_view(), name="Webinarqueries"),
            path('WebinarqueryResult/<str:email>/<str:option>/<str:year>', views.WebinarqueryResult.as_view(), name="WebinarqueryResult"),
            path('Sttpqueries', views.Sttpqueries.as_view(), name="Sttpqueries"),
            path('SttpqueryResult/<str:email>/<str:option>/<str:year>', views.SttpqueryResult.as_view(), name="SttpqueryResult"),
        ])),
        path('departmentQueries/', include([
            path('Paperqueries', views.PaperDeptQueries.as_view(), name="PaperDeptQueries"),
            path('Paperqueriesresult/<str:year>', views.PaperDeptQueriesResult.as_view(), name="PaperDeptQueriesResult"),
            path('Fdpqueries', views.FdpDeptQueries.as_view(), name="FdpDeptQueries"),
            path('Fdpqueriesresult/<str:year>', views.FdpDeptQueriesResult.as_view(), name="FdpDeptQueriesResult"),
            path('Workshopqueries', views.WorkDeptQueries.as_view(), name="WorkDeptQueries"),
            path('Workshopqueriesresult/<str:year>', views.WorkDeptQueriesResult.as_view(), name="WorkDeptQueriesResult"),
            path('GuestLecturequeries', views.GlDeptQueries.as_view(), name="GlDeptQueries"),
            path('GuestLecturequeriesresult/<str:year>', views.GlDeptQueriesResult.as_view(), name="GlDeptQueriesResult"),
            path('Webinarqueries', views.WebiDeptQueries.as_view(), name="WebiDeptQueries"),
            path('Webinarqueriesresult/<str:year>', views.WebiDeptQueriesResult.as_view(), name="WebiDeptQueriesResult"),
            path('Coursequeries', views.CourseDeptQueries.as_view(), name="CourseDeptQueries"),
            path('Coursequeriesresult/<str:year>', views.CourseDeptQueriesResult.as_view(), name="CourseDeptQueriesResult"),
            path('Sttpqueries', views.SttpDeptQueries.as_view(), name="SttpDeptQueries"),
            path('Sttpqueriesresult/<str:year>', views.SttpDeptQueriesResult.as_view(), name="SttpDeptQueriesResult"),
            path('PEqueries', views.PEQueries.as_view(), name="PEQueries"),
            path('PEQueryResult/<str:year>/<str:acadYear>/<str:sem>', views.PEQueryResult.as_view(), name="PEQueryResult"),
        ])),
        path('studentQueries/', include([
            path('completeSTUQuery',views.completeSTUQuery.as_view(),name='completeSTUQuery'),
            path('completeSTUResult/<str:PRN>',views.completeSTUResult.as_view(),name='completeSTUResult'),
            path('Paperqueries', views.stuPaperQueries.as_view(), name="StudentPaperQueries"),
            path('PaperqueryResult/<str:year>', views.stuPaperQueryResult.as_view(), name="StudentPaperqueryResult"),
            path('Coursequeries', views.stuOnlineCourseQueries.as_view(), name="StudentOnlineQueries"),
            path('OnlineCoursequeryResult/<str:year>', views.stuOnlineCourseQueryResult.as_view(),
                 name="StudentCoursequeryResult"),
            path('Competitionqueries', views.stuCompQueries.as_view(), name="StudentCompetitionQueries"),
            path('CompetitionqueryResult/<str:year>', views.stuCompQueryResult.as_view(),
                 name="StudentCompetitionqueryResult"),

            path('GREqueries', views.GREQueries.as_view(), name="GREQueries"),
            path('GREqueryResult/<str:year>', views.GREQueryResult.as_view(), name="GREQueryResult"),
            path('studentsUpdated', views.studentsUpdated.as_view(), name="studentsUpdated"),
            path('studentsUpdatedResult/<str:year>', views.studentsUpdatedResult.as_view(), name="studentsUpdatedResult"),
            path('studentsNotUpdated', views.studentsNotUpdated.as_view(), name="studentsNotUpdated"),
            path('studentsNotUpdatedResult/<str:year>', views.studentsNotUpdatedResult.as_view(), name="studentsNotUpdatedResult"),
            path('TOEFLqueries', views.TOEFLQueries.as_view(), name="TOEFLQueries"),
            path('TOEFLqueryResult/<str:year>', views.TOEFLQueryResult.as_view(), name="TOEFLQueryResult"),
            path('GATEqueries', views.GATEQueries.as_view(), name="GATEQueries"),
            path('GATEqueryResult/<str:year>', views.GATEQueryResult.as_view(), name="GATEQueryResult"),
            path('Startupqueries', views.StartupQueries.as_view(), name="StartupQueries"),
            path('StartupqueryResult/<str:year>', views.StartupQueryResult.as_view(), name="StartupQueryResult"),
            path('Internshipqueries', views.InternshipQueries.as_view(), name="InternshipQueries"),
            path('InternshipqueryResult/<str:year>/<str:type2>', views.InternshipQueryResult.as_view(),
                 name="InternshipQueryResult"),
            path('Placementqueries', views.PlacementQueries.as_view(), name="PlacementQueries"),
            path('PlacementqueryResult/<str:year>', views.PlacementQueryResult.as_view(), name="PlacementQueryResult"),
            path('Projectqueries', views.ProjectQueries.as_view(), name="ProjectQueries"),
            path('SocialProjectqueryResult/<str:year>', views.ProjectQueryResult.as_view(), name="SocialProjectQueryResult"),
            path('Graduationqueries', views.GraduationQueries.as_view(), name="GraduationQueries"),
            path('GraduationQueryResult/<str:yearOfEnrollment>-<str:yearOfGraduation>', views.GraduationQueryResult.as_view(), name="GraduationQueryResult"),
            path('PEStuqueries', views.PEStuQueries.as_view(), name="PEStuQueries"),
            path('PEStuQueryResult/<str:year>/<str:acadYear>/<str:sem>/<str:courseCode>', views.PEStuQueryResult.as_view(), name="PEStuQueryResult"),
        ])),
    ])),
]

