# Generated by Django 3.1.1 on 2021-02-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0016_student_isda'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sem', models.IntegerField(default=1, null=True)),
                ('courseName', models.CharField(default='FLAT', max_length=100)),
                ('courseCode', models.CharField(default='4CS101', max_length=20)),
                ('acadYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PETakenByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classteacher.pes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
