# Generated by Django 3.1.4 on 2021-03-24 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_elective'),
        ('classteacher', '0002_auto_20210324_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petakenbystudent',
            name='PE',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classteacher.pes'),
        ),
        migrations.AlterField(
            model_name='petakenbystudent',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
