# Generated by Django 3.1.4 on 2021-03-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_elective'),
        ('classteacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pes',
            name='courseCode',
            field=models.CharField(default='4CS101', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='petakenbystudent',
            name='PE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classteacher.pes'),
        ),
        migrations.AlterField(
            model_name='petakenbystudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
