# Generated by Django 3.1.4 on 2020-12-15 04:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gradexitsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(default='CSE', max_length=60)),
                ('startYear', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('endYear', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('uploadgradexitsurvey', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deptfeedbacksurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(default='CSE', max_length=60)),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('semester', models.IntegerField(default=2, null=True)),
                ('uploaddeptexitsurvey', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='courseexitsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Operating Systems', max_length=60)),
                ('coursecode', models.CharField(default='4CS203', max_length=25)),
                ('courseclass', models.IntegerField(default=4, null=True)),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year')),
                ('semester', models.IntegerField(default=2, null=True)),
                ('uploadcourseexitsurvey', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
