# Generated by Django 3.1.1 on 2021-01-29 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0002_deptfeedbacksurvey_courseclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexitsurvey',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='deptfeedbacksurvey',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='gradexitsurvey',
            name='endYear',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='gradexitsurvey',
            name='startYear',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='year'),
        ),
    ]
